### ISSUE TITLE
Activation error...

### ISSUE THREAD

**Issue by limikael** [tunapanda/wp-xapi-lrs#5]
Log:

Fatal error: Uncaught exception 'DatabaseException' with message 'Specified key was too long; max key length is 767 bytes' in /home/contemp6/public_html/lisn/wp-content/plugins/wp-xapi-lrs/ext/minixapi/MiniXapi.php:368 Stack trace: #0 /home/contemp6/public_html/lisn/wp-content/plugins/wp-xapi-lrs/wp-xapi-lrs.php(31): MiniXapi->install() #1 [internal function]: xapilrs_activate('') #2 /home/contemp6/public_html/lisn/wp-includes/class-wp-hook.php(298): call_user_func_array('xapilrs_activat...', Array) #3 /home/contemp6/public_html/lisn/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /home/contemp6/public_html/lisn/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/contemp6/public_html/lisn/wp-admin/plugins.php(166): do_action('activate_wp-xap...') #6 {main} thrown in /home/contemp6/public_html/lisn/wp-content/plugins/wp-xapi-lrs/ext/minixapi/MiniXapi.php on line 368

**Comment by foepsen** [comment]
Hi there! Actually I got the same issue while activating the plugin:

`Fatal error: Uncaught DatabaseException: Specified key was too long; max key length is 767 bytes in /var/www/html/wordpress/wp-content/plugins/wp-xapi-lrs/ext/minixapi/MiniXapi.php:368 Stack trace: #0 /var/www/html/wordpress/wp-content/plugins/wp-xapi-lrs/wp-xapi-lrs.php(31): MiniXapi->install() #1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(286): xapilrs_activate('') #2 /var/www/html/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /var/www/html/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /var/www/html/wordpress/wp-admin/plugins.php(174): do_action('activate_wp-xap...') #5 {main} thrown in /var/www/html/wordpress/wp-content/plugins/wp-xapi-lrs/ext/minixapi/MiniXapi.php on line 368`

Are there any solutions expectable? As this is the only plugin available for WP I would highly appreciate it!
